"use client";

import { useMemo, useState } from "react";
import { useReducedMotion } from "framer-motion";
import { Film, Loader2 } from "lucide-react";
import type { SurfaceComponent } from "@/lib/a2ui/surfaces/manager";
import { getAestheticCopy } from "@/lib/aesthetic/identity";
import type { AestheticId } from "@/lib/aesthetic/types";
import { useVideoConfigured, useVideoGeneration } from "@/lib/hooks/useVideoGeneration";
import { cn } from "@/lib/utils";
import { useSurfaceContext, type ComponentProps } from "../internal/context";
import { useResolve, useBaseAestheticId } from "../internal/binding";
import { childIdsOf } from "../internal/registry";

/**
 * Find generated-image urls that share a container with the given Video node, to
 * offer as Veo subject-reference images (e.g. a suspect's mugshot sitting in the
 * same Card as its footage). The surface is a flat id→component map with no
 * parent pointers, so we build a child→parent map once, walk up to the Video's
 * nearest ancestor, and collect `Image` descendants under it. Only same-origin
 * `/api/images/...` urls (real generated bytes) qualify; capped at 3 (Veo's max).
 */
function findSiblingImageUrls(
  videoId: string,
  components: Map<string, SurfaceComponent>,
  resolve: (value: unknown) => unknown
): string[] {
  // child id → parent id
  const parentOf = new Map<string, string>();
  for (const [id, comp] of components) {
    for (const childId of childIdsOf(comp)) parentOf.set(childId, id);
  }

  // Walk up from the video to its nearest ancestor container (one level up is
  // the common "Card { Image, Video }" case; we stop at the first parent and
  // also try the grandparent so a Column-wrapped pair is still caught).
  const ancestors: string[] = [];
  let cursor = parentOf.get(videoId);
  let hops = 0;
  while (cursor && hops < 2) {
    ancestors.push(cursor);
    cursor = parentOf.get(cursor);
    hops += 1;
  }

  const urls: string[] = [];
  const seen = new Set<string>();
  const collectImagesUnder = (rootId: string) => {
    const stack = [rootId];
    const visited = new Set<string>();
    while (stack.length > 0) {
      const id = stack.pop()!;
      if (visited.has(id)) continue;
      visited.add(id);
      const comp = components.get(id);
      if (!comp) continue;
      if (comp.id !== videoId && comp.component === "Image") {
        const raw = String(resolve((comp as { url?: unknown }).url) ?? "");
        if (raw.startsWith("/api/images/") && !seen.has(raw)) {
          seen.add(raw);
          urls.push(raw);
        }
      }
      for (const childId of childIdsOf(comp)) stack.push(childId);
    }
  };

  for (const ancestorId of ancestors) {
    collectImagesUnder(ancestorId);
    if (urls.length > 0) break; // nearest container with images wins
  }
  return urls.slice(0, 3);
}

export function VideoRenderer({ component }: ComponentProps) {
  const resolve = useResolve();
  const baseAestheticId = useBaseAestheticId();
  const { surface } = useSurfaceContext();
  const video = component as SurfaceComponent & {
    url?: unknown;
    poster?: unknown;
    accessibility?: { label?: unknown };
  };
  const url = String(resolve(video.url) ?? "");
  const label = video.accessibility?.label ? String(resolve(video.accessibility.label)) : undefined;
  // Preview frame (A2UI v1.0 posterUrl). Only used for a real playable clip; the
  // generation placeholder has no frame to show yet.
  const posterRaw = video.poster ? String(resolve(video.poster)) : "";
  const poster = posterRaw.trim() || undefined;

  const referenceImageUrls = useMemo(
    () => findSiblingImageUrls(video.id, surface.components, resolve),
    [video.id, surface.components, resolve]
  );

  // A real playable source plays directly: an absolute/served/data/blob URL, or
  // any root-relative path (e.g. "/clip.mp4", "/assets/x.webm"). Anything else
  // (free-text) is treated as a generation prompt below.
  const isPlayable =
    url.startsWith("/") ||
    url.startsWith("http://") ||
    url.startsWith("https://") ||
    url.startsWith("data:") ||
    url.startsWith("blob:");

  if (isPlayable) {
    return (
      <video
        src={url}
        controls
        poster={poster}
        aria-label={label}
        className="block w-full max-w-full rounded-[var(--aesthetic-radius,2px)] border border-[var(--aesthetic-border)]/40 sepia-[0.15]"
      />
    );
  }

  // Otherwise `url` (or the accessibility label) is a prompt, NOT a source.
  // Video is expensive + on demand, so it is NEVER auto-generated — the user
  // must explicitly trigger it here.
  const prompt = url.trim() || label?.trim() || "";
  return (
    <VideoGenerator
      prompt={prompt}
      aestheticId={baseAestheticId}
      label={label}
      referenceImageUrls={referenceImageUrls}
    />
  );
}

/**
 * On-demand generate affordance for a Video component whose source is still a
 * prompt. Renders the in-world "FOOTAGE PENDING" placeholder plus an explicit
 * Generate button (disabled when no API key is configured), shows live progress
 * while Veo runs, then swaps in the finished clip. Reduced-motion safe (no
 * spinner animation when the user opts out).
 */
function VideoGenerator({
  prompt,
  aestheticId,
  label,
  referenceImageUrls = [],
}: {
  prompt: string;
  aestheticId?: string;
  label?: string;
  /** Sibling generated-image urls offered as Veo subject references. */
  referenceImageUrls?: string[];
}) {
  const { status, videoUrl, error, generate } = useVideoGeneration();
  const configured = useVideoConfigured();
  const prefersReducedMotion = useReducedMotion();

  // Pre-checked when references exist: the suspect-consistency case is the point
  // of having them. The user can opt out (plain text-to-video, any duration).
  const hasReferences = referenceImageUrls.length > 0;
  const [useReferences, setUseReferences] = useState(true);

  if (status === "ready" && videoUrl) {
    return (
      <video
        src={videoUrl}
        controls
        aria-label={label}
        className="block w-full max-w-full rounded-[var(--aesthetic-radius,2px)] border border-[var(--aesthetic-border)]/40 sepia-[0.15]"
      />
    );
  }

  const busy = status === "starting" || status === "pending";
  const disabled = busy || !prompt || configured === false;
  const disabledReason =
    configured === false
      ? "Set GOOGLE_GENERATIVE_AI_API_KEY to enable video"
      : !prompt
        ? "No prompt to generate from"
        : undefined;
  const applyReferences = hasReferences && useReferences;
  const refCount = referenceImageUrls.length;

  return (
    <div className="flex flex-col gap-2 rounded-[var(--aesthetic-radius,2px)] border border-[var(--aesthetic-border)]/40 bg-[var(--aesthetic-background)]/35 px-4 py-3">
      <div className="flex items-center gap-2 font-mono text-xs uppercase tracking-widest text-[var(--aesthetic-text)]/70">
        <Film className="h-3.5 w-3.5 shrink-0" aria-hidden />
        {busy
          ? "Developing footage…"
          : getAestheticCopy(aestheticId as AestheticId | undefined).videoPending}
      </div>
      {prompt && (
        <p className="line-clamp-2 font-mono text-[11px] text-[var(--aesthetic-text)]/45">
          {prompt}
        </p>
      )}
      {hasReferences && !busy && (
        <label className="flex items-start gap-2 font-mono text-[11px] text-[var(--aesthetic-text)]/60">
          <input
            type="checkbox"
            checked={useReferences}
            onChange={(e) => setUseReferences(e.target.checked)}
            className="mt-0.5 accent-[var(--aesthetic-accent)]"
          />
          <span>
            Match {refCount === 1 ? "the image" : `${refCount} images`} above
            <span className="text-[var(--aesthetic-text)]/40"> (forces an 8s clip)</span>
          </span>
        </label>
      )}
      {status === "failed" && error && (
        <p className="font-mono text-[11px] text-[var(--aesthetic-error)]">{error}</p>
      )}
      <button
        type="button"
        onClick={() =>
          generate(prompt, {
            aestheticId,
            ...(applyReferences ? { referenceImageUrls } : {}),
          })
        }
        disabled={disabled}
        title={disabledReason}
        aria-label="Generate footage"
        className={cn(
          "inline-flex w-fit items-center gap-1.5 rounded-[var(--aesthetic-radius,2px)] border px-3 py-1.5 font-typewriter text-[11px] uppercase tracking-wider transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--aesthetic-accent)]",
          disabled
            ? "cursor-not-allowed border-[var(--aesthetic-border)]/40 text-[var(--aesthetic-text)]/40"
            : "border-[var(--aesthetic-accent)]/50 bg-[var(--aesthetic-accent)]/10 text-[var(--aesthetic-accent)] hover:bg-[var(--aesthetic-accent)]/25"
        )}
      >
        {busy ? (
          <Loader2
            className={cn("h-3.5 w-3.5", !prefersReducedMotion && "animate-spin")}
            aria-hidden
          />
        ) : (
          <Film className="h-3.5 w-3.5" aria-hidden />
        )}
        {busy ? "Generating" : status === "failed" ? "Retry" : "Generate footage"}
      </button>
    </div>
  );
}
